### ISSUE TITLE
Url Change

### ISSUE THREAD

**Issue by krazynez** [Dejvino/pinephone-arch-install#1]
Line 42 of common.h 
`KERNEL_URL=https://xff.cz/kernels/5.6/pp.tar.gz`

should be now 
`KERNEL_URL=https://xff.cz/kernels/5.8/pp2.tar.gz`

**Comment by ninjasource** [comment]
I think that using kernel 5.8 is causing issue [#3 ](url): No uboot.bin file found

**Comment by krazynez** [comment]
Yeah I grabbed uboot.bin from the manjaro version I think. I will have to look into it again to make sure.

EDIT: u-boot was in readme
https://megous.com/git/u-boot/

**Comment by Dejvino** [comment]
Looks like the kernel archive contains `uboot.bin` once again, I was able to run through all the commands successfully today with the updated URL in commit c6c0bdd.
Thanks!
