### ISSUE TITLE
No uboot.bin found when running 04-flash_kernel.sh

### ISSUE THREAD

**Issue by ninjasource** [Dejvino/pinephone-arch-install#3]
Hi thanks for your scripts, I wonder if you could help with the error message below.

I got the following error message when running the 04-flash_kernel.sh script:
```
Flashing the bootloader to SD Card /dev/sdb:
Are you sure you want to continue? [Y/n]: Y
Flashing...
dd: failed to open 'uboot.bin': No such file or directory
ERROR: Could not flash the bootloader
```

Note that I am using the 5.8 kernel and not the 5.6 kernel as per the previous stated issue. The 5.6 kernel is no longer available.

**Comment by Dejvino** [comment]
Should be part of the kernel archive once again, as mentioned in issue #1.

**Comment by ninjasource** [comment]
Brilliant, it works now. Thanks!
